export const displayPopType = {
  POPUP_SHORT_FORM_PLAYER: { name: "POPUP_SHORT_FORM_PLAYER" },
  POPUP_MYPROFILE: { name: "POPUP_MYPROFILE" },
  POPUP_LOGIN: { name: "POPUP_LOGIN" },
  POPUP_PURCHASE_POINT: { name: "POPUP_PURCHASE_POINT" },
  POPUP_SERIES_KEEP: { name: "POPUP_SERIES_KEEP" },
  POPUP_SERIES_WATCH: { name: "POPUP_SERIES_WATCH" },
  POPUP_SIGN_UP: { name: "POPUP_SIGN_UP" },
  POPUP_SERIES_LIST: { name: "POPUP_SERIES_LIST" }
}

export const uiPopType = {
  UI_LEFT_MENU: { name: "UI_LEFT_MENU"},
  UI_LOGIN: {name: "UI_LOGIN"},
}